#!/bin/bash
# Routine chain for one project, from a fresh re-tick with whatever observer config is installed.
#
# Three things here were learned the hard way and must not be simplified away:
#  - the timestep comes from the project, never pinned (LongWalk ticks at 0.002, the rest 0.005);
#  - plotAndFormatResults is asked to write its outputs, without which the evaluation copies stale
#    trajectories and the *_loc_vel.pickle velocity files are never refreshed;
#  - the RI-EKF baseline is the OFFLINE parse, not the in-tick plugin, which emits one row every
#    two iterations on the 500 Hz LongWalk log and leaves zero-norm quaternions in the merge.
set -u
HERE=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$HERE/../.." && pwd)
WORK="$ROOT/results/paper-rebuild"
cd "$ROOT" || exit 1
p=$1
proj="$ROOT/Projects/$p"
out="$proj/output_data"
stage="$WORK/retick/$p.bin"
mkdir -p "$WORK/retick"
step() { echo "   [$(date +%H:%M:%S)] $*"; }

ts=$(.venv/bin/python -c "import sys;sys.path.insert(0,'scripts');import kinetics_eval as ke;print(ke.project_timestep(ke.ROOT/'Projects'/'$p'))") || exit 1
echo "[$(date +%H:%M:%S)] $p (timestep $ts)"

# Passthrough in the run's configuration HOME already contains every observer instance.

step "re-tick"
.venv/bin/python "$HERE/retick_routine.py" "$p" "$stage" || { echo "[$p] RE-TICK FAILED"; exit 1; }

n=$(mc_bin_utils show "$stage" 2>/dev/null | grep -c "MocapAligner")
[ "$n" -gt 0 ] || { echo "[$p] ABANDON: le log re-tique n'a pas la mocap"; exit 1; }

step "allegement -> logReplay.bin"
keys=$(cd scripts && ../env/bin/python lightenOutputBin.py "$proj" "$stage") || exit 1
eval scripts/routine_scripts/lightenBin.sh "$stage" "$out/logReplay.bin" $keys > /dev/null \
  || { echo "[$p] LIGHTEN FAILED"; exit 1; }

# The re-ticked log is 23 GB for LongWalk and is never read again once lightened. Over the 58
# chains of a full rebuild, keeping them fills the disk.
rm -f "$stage"

step "mc_bin_to_log"
( cd "$out" && rm -f logReplay.csv && mc_bin_to_log logReplay.bin ) > /dev/null 2>&1 \
  || { echo "[$p] BIN_TO_LOG FAILED"; exit 1; }

# The orientation-error project re-ticks the very controllerLog.bin of HRP5_MultiContact_1 (same
# md5, same row count) and the RI-EKF does not depend on the Kinetics Observer's tuning, so that
# project's parse is exactly this one's. It cannot simply be dropped: plotAndFormatResults needs
# posFbImu, which it only defines inside its RI-EKF block.
# Verified by md5: each *_WO_LeftHand project re-ticks byte-identical raw data to its numbered
# twin, and the orientation-error project re-ticks MultiContact_1's.
source=${p%_WO_LeftHand}
[ "$p" = "HRP5_MultiContact_ContactInitOriError" ] && source=HRP5_MultiContact_1
# A variant that changes what the SENSORS deliver invalidates the cached parse, so it has to be
# rebuilt from the input this very tick just wrote. KO_REBUILD_HARTLEY carries the robot name.
if [ -n "${KO_REBUILD_HARTLEY:-}" ]; then
  step "RI-EKF hors ligne: reconstruction (${KO_REBUILD_HARTLEY})"
  "$HERE/rebuild_hartley.sh" "$source" "$KO_REBUILD_HARTLEY" || exit 1
fi
offline="$WORK/hartley/$source-HartleyOutput.csv"
if [ -f "$offline" ]; then
  step "RI-EKF hors ligne ($source)"
  cp "$offline" "$out/HartleyOutputCSV.csv" || exit 1
else
  echo "[$p] ABANDON: pas de parse RI-EKF hors ligne pour $source"; exit 1
fi

cd scripts || exit 1
for cmd in \
  "extractLightReplayVersion.py $proj" \
  "repair_mc_rtc_skipped_iters.py $ts $proj" \
  "initialize_datas.py $ts $proj true" \
  "resampleMocapAndExtractPose.py false y $proj" \
  "crossCorrelation.py false y $proj" \
  "matchInitPose.py 0 false y $proj" \
  "plotAndFormatResults.py false $proj True" ; do
  step "${cmd%% *}"
  ../env/bin/python $cmd > "$WORK/retick/$p.${cmd%%.py*}.log" 2>&1 \
    || { echo "[$p] ${cmd%% *} FAILED - voir $WORK/retick/$p.${cmd%%.py*}.log"
         tail -6 "$WORK/retick/$p.${cmd%%.py*}.log"; exit 1; }
done
cd "$ROOT" || exit 1

# Only the thirteen scored datasets carry predefined sublengths; the hand-removal and
# orientation-error projects feed a figure or a table instead.
if grep -q "predefined_sublengths" "$proj/projectConfig.yaml" 2>/dev/null; then
  # VALINOR is scored too: its trajectory is regenerated by every chain, but its RPG evaluation
  # was never rerun, so the paper carried August numbers for it while everything else moved.
  # Score whatever this tick actually produced, rather than a fixed list: every Kinetics Observer
  # variant now runs as its own instance in the same tick, and initialize_datas.py already derives
  # observers_infos.yaml from the columns present in the log. Reading it back keeps the two in
  # step, so adding an instance to the controller is enough to get it scored.
  observers=$(env/bin/python -c "
import yaml
kept = yaml.safe_load(open('$out/observers_infos.yaml'))['observers']
print(' '.join(o for o in kept if o not in ('Mocap', 'Control')))")
  step "RPG ($observers)"
  "$HERE/reeval.sh" "$p" $observers > "$WORK/retick/$p.rpg.log" 2>&1 \
    || { echo "[$p] RPG FAILED"; exit 1; }
fi
echo "[$(date +%H:%M:%S)] $p OK"
